version: "3.5"

services:
  php:
    build:
      context: "./php/"
      args:
        PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}:/var/www/html/
    environment:
      MYSQL_HOST: "${DB_HOST}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      INSTANCE_NAME: "${INSTANCE_NAME}"
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    container_name: ${DOCKER_IMAGE_PREFIX}php
    restart: always
    platform: linux/amd64

  apache:
    build:
      context: "./apache/"
      args:
        APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "${EXTERNAL_APACHE_PORT}:80"
    volumes:
      - ./public_html:/var/www/html/
      - ./public_html/ecodesign:/var/www/html/ecodesign
    container_name: ${DOCKER_IMAGE_PREFIX}apache
    restart: always
    platform: linux/amd64

  mysql:
    image: mysql:${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "${EXTERNAL_MYSQL_PORT}:3306"
    volumes:
      - ./mysql/data/:/var/lib/mysql
    networks:
      - backend
    environment:
      TZ: "${TZ}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    container_name: ${DOCKER_IMAGE_PREFIX}mysql
    platform: linux/amd64

  mailcatcher:
    image: dockage/mailcatcher
    restart: on-failure
    networks:
      - backend
    ports:
      - "1080:1080"
      - "1025:1025"
    platform: linux/amd64
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "${EXTERNAL_PMA_PORT}:80"
    networks:
      - backend
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    container_name: "${DOCKER_IMAGE_PREFIX}phpmyadmin"
    platform: linux/amd64

networks:
  frontend:
    name: ${DOCKER_IMAGE_PREFIX}frontend
  backend:
    name: ${DOCKER_IMAGE_PREFIX}backend

volumes:
  data: