version: "3.5"

services:
  php:
    build:
      context: "./php/"
      args:
        PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}:/var/www/html/
    environment:
      MYSQL_HOST: "${DB_HOST}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      INSTANCE_NAME: "${INSTANCE_NAME}"
    container_name: ${DOCKER_IMAGE_PREFIX}php
    restart: always

  apache:
    build:
      context: "./apache/"
      args:
        APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "${EXTERNAL_APACHE_PORT}:80"
    volumes:
      - ${PROJECT_ROOT}:/var/www/html/
    container_name: ${DOCKER_IMAGE_PREFIX}apache
    restart: always

  mariadb:
    image: mariadb
    restart: always
    ports:
      - "${EXTERNAL_MYSQL_PORT}:3306"
    # volumes:
    #   - ./mysql/data/:/var/lib/mysql
    networks:
      - backend
    environment:
      TZ: "${TZ}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: "${DOCKER_IMAGE_PREFIX}mariadb"
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "${EXTERNAL_PMA_PORT}:80"
    networks:
      - backend
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_VERBOSE: "${DB_NAME}"
      PMA_USER: "${DB_USERNAME}"
      PMA_PASSWORD: "${DB_PASSWORD}"
      PMA_PORT: "${EXTERNAL_MYSQL_PORT}"
    container_name: "${DOCKER_IMAGE_PREFIX}phpmyadmin"

networks:
  frontend:
    name: ${DOCKER_IMAGE_PREFIX}frontend
  backend:
    name: ${DOCKER_IMAGE_PREFIX}backend

volumes:
  data: